create table "public"."tenant_permission" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "service_user" bigint not null,
    "tenant" text not null
);


alter table "public"."tenant_permission" enable row level security;

CREATE UNIQUE INDEX tenant_permission_pkey ON public.tenant_permission USING btree (id);

alter table "public"."tenant_permission" add constraint "tenant_permission_pkey" PRIMARY KEY using index "tenant_permission_pkey";

alter table "public"."tenant_permission" add constraint "tenant_permission_service_user_fkey" FOREIGN KEY (service_user) REFERENCES service_users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tenant_permission" validate constraint "tenant_permission_service_user_fkey";

alter table "public"."tenant_permission" add constraint "tenant_permission_tenant_fkey" FOREIGN KEY (tenant) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tenant_permission" validate constraint "tenant_permission_tenant_fkey";

grant delete on table "public"."tenant_permission" to "anon";

grant insert on table "public"."tenant_permission" to "anon";

grant references on table "public"."tenant_permission" to "anon";

grant select on table "public"."tenant_permission" to "anon";

grant trigger on table "public"."tenant_permission" to "anon";

grant truncate on table "public"."tenant_permission" to "anon";

grant update on table "public"."tenant_permission" to "anon";

grant delete on table "public"."tenant_permission" to "authenticated";

grant insert on table "public"."tenant_permission" to "authenticated";

grant references on table "public"."tenant_permission" to "authenticated";

grant select on table "public"."tenant_permission" to "authenticated";

grant trigger on table "public"."tenant_permission" to "authenticated";

grant truncate on table "public"."tenant_permission" to "authenticated";

grant update on table "public"."tenant_permission" to "authenticated";

grant delete on table "public"."tenant_permission" to "service_role";

grant insert on table "public"."tenant_permission" to "service_role";

grant references on table "public"."tenant_permission" to "service_role";

grant select on table "public"."tenant_permission" to "service_role";

grant trigger on table "public"."tenant_permission" to "service_role";

grant truncate on table "public"."tenant_permission" to "service_role";

grant update on table "public"."tenant_permission" to "service_role";


